language: node_js
node_js:
- '8'
branches:
  only:
  - source
deploy:
  provider: pages
  name: notoriousb1t
  email: christopher.j.wallis@gmail.com
  target_branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: source
